-- Backfill NULL tenantId rows to the default tenant (subdomain='default').
-- Implements the rule: rows with tenantId IS NULL "belong to" the default
-- MedCore tenant, so exact-match tenant scoping (tenantScopedPrisma) shows
-- them ONLY to the default tenant and hides them from every other tenant.
--
-- Idempotent: the WHERE "tenantId" IS NULL guard makes re-runs a no-op.
-- Excluded (NULL is legitimate platform/system telemetry — reattributing it
-- to a real tenant would misattribute platform-operator activity):
--   audit_logs, request_metrics, usage_events, scheduled_task_runs.

DO $$
DECLARE
  default_tenant_id TEXT;
BEGIN
  SELECT id INTO default_tenant_id FROM tenants WHERE subdomain = 'default' LIMIT 1;
  IF default_tenant_id IS NULL THEN
    RAISE NOTICE 'No default tenant (subdomain=default) found; skipping backfill.';
    RETURN;
  END IF;

  UPDATE "abha_links" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "adherence_dose_logs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "adherence_schedules" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "admissions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "advance_directives" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "advance_payments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ai_scribe_sessions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ai_triage_sessions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ambulance_fuel_logs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ambulance_trips" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ambulances" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "anc_visits" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "anesthesia_records" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "antenatal_cases" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "appointment_remarks" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "appointments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "asset_assignments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "asset_maintenance" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "asset_transfers" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "assets" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "beds" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "bill_explanations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_cross_matches" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_donations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_donors" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_requests" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_screenings" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_temperature_logs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "blood_units" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "branches" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "calendar_events" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "campaign_audiences" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "campaign_sends" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "campaigns" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "care_contexts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chat_messages" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chat_participants" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chat_rooms" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chronic_care_alerts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chronic_care_checkins" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chronic_care_cohorts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chronic_care_plans" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "chronic_conditions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "claim_denial_history" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "cohort_members" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "cohort_sequence_steps" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "cohorts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "complaints" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "component_separations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "consent_artefacts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "consultations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "controlled_substance_register" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "coordinated_visits" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "credit_notes" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "discount_approvals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "doc_qa_reports" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "doctor_favourite_medicines" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "doctor_schedules" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "doctors" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "donor_deferrals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "dpdp_erasure_requests" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "emergency_cases" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "expense_budgets" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "expenses" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "family_history" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "feedback_sentiment" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "feeding_logs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "fraud_alerts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "front_desk_calls" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "grns" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "growth_records" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "health_packages" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "holidays" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "immunizations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "implants" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "insurance_claims" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "insurance_claims_v2" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "insurance_providers" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "inventory_items" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "invoices" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ipd_intake_output" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ipd_vitals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "lab_orders" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "lab_qc_entries" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "lab_report_explanations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "lab_results" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "lead_activities" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "leads" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "leave_balances" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "leave_requests" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "med_reconciliations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "medication_administrations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "medication_incidents" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "medication_orders" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "milestone_records" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "notification_broadcasts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "notification_schedules" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "notification_templates" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "notifications" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "nps_daily_rollup" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "nurse_rounds" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "operating_theaters" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "overtime_records" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "package_purchases" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "partographs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_allergies" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_belongings" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_data_exports" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_documents" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_family_links" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_feedback" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patient_otp_challenges" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "patients" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "payment_plan_installments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "payment_plans" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "payments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "pharmacy_returns" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "platform_invoices" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "post_op_observations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "postnatal_visits" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "preauth_requests" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "prescription_templates" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "prescriptions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "previsit_checklists" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "purchase_orders" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "radiology_reports" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "radiology_studies" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "referral_commissions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "referrals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "report_runs" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "schedule_overrides" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "scheduled_reports" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "shared_links" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "staff_certifications" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "staff_roster_proposals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "staff_shifts" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "stock_movements" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "stock_transfers" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "supplier_catalog_items" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "supplier_payments" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "suppliers" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "support_tickets" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "surgeries" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "symptom_diary_entries" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "telemedicine_sessions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "tenant_subscriptions" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "tenant_usage_daily" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "ultrasound_records" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "user_invites" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "users" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "visitor_blacklist" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "visitors" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "vitals" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "waitlist_entries" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "wards" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "whatsapp_config" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "whatsapp_conversations" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
  UPDATE "whatsapp_messages" SET "tenantId" = default_tenant_id WHERE "tenantId" IS NULL;
END $$;
