/**
 * Visitor history seed — historical check-in/check-out records for the
 * visitor management dashboard (30-day rolling window) plus 5 blacklist
 * entries.
 *
 * Idempotency contract (2026-05-10): safe to re-run on a populated demo
 * without creating duplicate visitor rows or blacklist entries.
 *
 *   - Visitors: stable passNumber `VIS-HIST-SEED-${NNNN}` namespaced
 *     prefix, distinct from BOTH the live production format
 *     (`VIS<digits>-<YYYYMMDD>`, generated by apps/api/src/routes/visitors.ts
 *     `nextPassNumber()`) AND the ops-enhancement seed prefix
 *     (`VIS-OPS-NNNN` from seed-ops-enhancements.ts). Re-runs do
 *     findUnique({ where: { passNumber } }) skip-or-create — leverages
 *     the existing @@unique on Visitor.passNumber.
 *   - Blacklist: findFirst({ where: { idProofNumber } }) (or phone when
 *     no idProof) skip-or-create. Already idempotent pre-2026-05-10.
 *   - All randomness driven by a deterministic mulberry32 PRNG so
 *     check-in dates / durations / purposes / patient assignments stay
 *     stable across runs (matches seed-realistic.ts pattern). Re-runs
 *     against a partially-seeded DB pick up exactly where they left off.
 *   - Does NOT touch the live `next_visitor_pass` SystemConfig (or any
 *     production passNumber counter) — the seed-namespaced prefix means
 *     the live counter never advances from this seed running.
 *
 * Wired into scripts/deploy.sh step 8o. Failures are non-fatal
 * (matches the policy of every other deploy-time fixture seed).
 */
import { PrismaClient, VisitorPurpose, Role } from "@prisma/client";

const prisma = new PrismaClient();

// Deterministic mulberry32 PRNG — same fixed-seed pattern as
// seed-realistic.ts so re-runs pick the same content/dates/durations
// even if some rows already exist (partial-run recovery).
const SEED = 0xb15d8842;
let _rngState = SEED;
function rng(): number {
  _rngState |= 0;
  _rngState = (_rngState + 0x6D2B79F5) | 0;
  let t = Math.imul(_rngState ^ (_rngState >>> 15), 1 | _rngState);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}

function randomItem<T>(arr: T[]): T {
  return arr[Math.floor(rng() * arr.length)];
}

function randomInt(min: number, max: number) {
  return Math.floor(rng() * (max - min + 1)) + min;
}

const VISITOR_NAMES = [
  "Ramesh Kulkarni", "Sunita Patil", "Deepak Bhosale", "Priya Iyer", "Vijay Rao",
  "Manisha Shah", "Anil Kumar", "Kavita Desai", "Sanjay Verma", "Nandini Nair",
  "Rahul Joshi", "Meena Gupta", "Harish Menon", "Rekha Sharma", "Ashok Pandey",
  "Divya Malhotra", "Bharat Singh", "Geeta Reddy", "Mohan Das", "Lakshmi Pillai",
  "Nitin Chavan", "Swati Jain", "Suresh Yadav", "Anita Deshpande", "Prakash Shetty",
  "Kiran Agarwal", "Manoj Gaikwad", "Fatima Khan", "Arun Mishra", "Neha Kapoor",
];

const BLACKLIST_REASONS = [
  "Aggressive behavior towards staff — asked to leave premises",
  "Attempted to bring prohibited items into ICU ward",
  "History of disturbing patients in maternity ward",
  "Multiple complaints from staff regarding inappropriate conduct",
  "Impersonated a relative to gain access — security incident",
];

const DEPARTMENTS = [
  "ICU", "Ward A", "Ward B", "Maternity", "Pediatrics", "OPD", "Emergency",
  "Administration", "Lab", "Pharmacy",
];

const ID_PROOF_TYPES = ["AADHAAR", "DRIVING_LICENSE", "VOTER_ID", "PAN_CARD", "PASSPORT"];

// Total seeded historical visitor rows. Stable across runs — seed indexes
// 1..TOTAL_VISITOR_ROWS each map to a deterministic row.
const TOTAL_VISITOR_ROWS = 50;

async function main() {
  console.log("\n=== Seeding Visitor History (idempotent) ===\n");

  // Order by mrNumber for stable patient assignment across re-runs (the
  // Patient model has no createdAt; mrNumber is @unique and stable).
  const patients = await prisma.patient.findMany({ take: 20, orderBy: { mrNumber: "asc" } });
  const adminUsers = await prisma.user.findMany({
    where: { role: { in: [Role.ADMIN, Role.RECEPTION] }, isActive: true },
    take: 3,
    orderBy: { createdAt: "asc" },
  });
  const addedBy = adminUsers[0]?.id;

  // Deterministic anchor: today at midnight UTC (so re-runs within the
  // same calendar day produce stable check-in timestamps).
  const todayUtcMidnight = new Date();
  todayUtcMidnight.setUTCHours(0, 0, 0, 0);
  const now = todayUtcMidnight.getTime();

  // Some returning visitors (same phone across multiple entries)
  const returningPool = [
    { name: "Rakesh Khanna", phone: "9900112211" },
    { name: "Sunita Patil", phone: "9900112212" },
    { name: "Mohan Das", phone: "9900112213" },
  ];

  let visitorsCreated = 0;
  let visitorsSkipped = 0;

  for (let i = 0; i < TOTAL_VISITOR_ROWS; i++) {
    // Stable seed-namespaced passNumber. Distinct from the live production
    // format (VIS<digits>-<YYYYMMDD>) and from the ops-enhancement seed
    // (VIS-OPS-NNNN).
    const passNumber = `VIS-HIST-SEED-${String(i + 1).padStart(4, "0")}`;

    const exists = await prisma.visitor.findUnique({
      where: { passNumber },
      select: { id: true },
    });
    if (exists) {
      visitorsSkipped++;
      // Burn the rng rolls this row would have consumed so subsequent
      // unseeded rows still pick deterministically aligned values.
      for (let r = 0; r < 8; r++) rng();
      continue;
    }

    // ~20% are returning visitors
    const isReturning = rng() < 0.2 && returningPool.length > 0;
    const rv = isReturning ? randomItem(returningPool) : null;

    const name = rv ? rv.name : randomItem(VISITOR_NAMES);
    const phone = rv ? rv.phone : `98${randomInt(10000000, 99999999)}`;

    // Spread over last 30 days
    const daysOffset = randomInt(0, 30);
    const hourOfDay = randomInt(8, 20);
    const checkInMs = now - daysOffset * 24 * 3600_000 - (24 - hourOfDay) * 3600_000 + randomInt(0, 59) * 60_000;
    const checkInAt = new Date(checkInMs);

    // Duration: 15min to 8h, most 30-120 min
    const durationMin = (() => {
      const r = rng();
      if (r < 0.1) return randomInt(15, 30);
      if (r < 0.7) return randomInt(30, 120);
      if (r < 0.95) return randomInt(120, 300);
      return randomInt(300, 480);
    })();
    const checkOutAt =
      daysOffset === 0 && rng() < 0.3
        ? null // still on-site
        : new Date(checkInAt.getTime() + durationMin * 60_000);

    // Purpose distribution: PATIENT_VISIT dominates
    const purpose: VisitorPurpose = (() => {
      const r = rng();
      if (r < 0.65) return VisitorPurpose.PATIENT_VISIT;
      if (r < 0.8) return VisitorPurpose.APPOINTMENT;
      if (r < 0.9) return VisitorPurpose.MEETING;
      if (r < 0.96) return VisitorPurpose.DELIVERY;
      return VisitorPurpose.OTHER;
    })();

    const patientId =
      purpose === VisitorPurpose.PATIENT_VISIT && patients.length > 0
        ? patients[i % patients.length].id // deterministic — round-robin by row index
        : null;

    await prisma.visitor.create({
      data: {
        passNumber,
        name,
        phone,
        idProofType: randomItem(ID_PROOF_TYPES),
        idProofNumber: `${randomInt(1000, 9999)}-${randomInt(1000, 9999)}-${randomInt(1000, 9999)}`,
        patientId: patientId ?? undefined,
        purpose,
        department: randomItem(DEPARTMENTS),
        checkInAt,
        checkOutAt,
        notes:
          purpose === VisitorPurpose.DELIVERY
            ? randomItem(["Medical supplies delivery", "Food delivery", "Courier package"])
            : purpose === VisitorPurpose.MEETING
            ? randomItem(["Vendor meeting", "Interview candidate", "External consultant"])
            : null,
      },
    });
    visitorsCreated++;
  }

  // Blacklist entries (already idempotent — kept as-is).
  const blacklistEntries = [
    { name: "Kabir Razdan", phone: "9100000001", idProofNumber: "5555-1111-2222" },
    { name: "Unknown — Incident 2025-11-03", phone: "9100000002", idProofNumber: "3456-7890-1234" },
    { name: "Satish Kumar (alias)", phone: "9100000003", idProofNumber: "9999-0000-1111" },
    { name: "Vijay Shah", phone: "9100000004", idProofNumber: null },
    { name: "Unnamed — Maternity incident 2026-02", phone: "9100000005", idProofNumber: null },
  ];

  let blacklisted = 0;
  let blacklistSkipped = 0;
  for (let i = 0; i < blacklistEntries.length; i++) {
    const entry = blacklistEntries[i];
    const reason = BLACKLIST_REASONS[i % BLACKLIST_REASONS.length];
    const existing = entry.idProofNumber
      ? await prisma.visitorBlacklist.findFirst({ where: { idProofNumber: entry.idProofNumber } })
      : await prisma.visitorBlacklist.findFirst({ where: { phone: entry.phone } });
    if (existing) {
      blacklistSkipped++;
      continue;
    }

    await prisma.visitorBlacklist.create({
      data: {
        name: entry.name,
        phone: entry.phone,
        idProofType: entry.idProofNumber ? "AADHAAR" : null,
        idProofNumber: entry.idProofNumber,
        reason,
        addedBy: addedBy ?? "system",
      },
    });
    blacklisted++;
  }

  console.log(`\n  Visitors created:      ${visitorsCreated}`);
  console.log(`  Visitors skipped:      ${visitorsSkipped} (idempotent re-run)`);
  console.log(`  Blacklist created:     ${blacklisted}`);
  console.log(`  Blacklist skipped:     ${blacklistSkipped} (idempotent re-run)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
