import { Page, APIRequestContext, expect } from "@playwright/test";

/**
 * API base URL used for server-side login.
 * Derived from E2E_API_URL, or falls back to localhost:4000/api/v1.
 */
export const API_BASE =
  process.env.E2E_API_URL || "http://localhost:4000/api/v1";

export type Role = "ADMIN" | "DOCTOR" | "NURSE" | "RECEPTION" | "PATIENT";

export interface Credentials {
  email: string;
  password: string;
}

/**
 * Seeded demo credentials (from packages/db/src/seed-realistic.ts).
 * Tests that modify data should rely on faker and should be idempotent.
 */
export const CREDS: Record<Role, Credentials> = {
  ADMIN: { email: "admin@medcore.local", password: "admin123" },
  DOCTOR: { email: "dr.sharma@medcore.local", password: "doctor123" },
  NURSE: { email: "nurse@medcore.local", password: "nurse123" },
  RECEPTION: { email: "reception@medcore.local", password: "reception123" },
  // Patient credentials are generated by the realistic seeder in the form
  // patient{N}@medcore.local / patient123 — patient1@ always exists.
  PATIENT: { email: "patient1@medcore.local", password: "patient123" },
};

/**
 * POST /auth/login against the API and return the access token.
 * Uses page.request so cookies / rate-limit IP matches browser context.
 */
export async function apiLogin(
  request: APIRequestContext,
  creds: Credentials
): Promise<{ token: string; refresh: string; user: any }> {
  const res = await request.post(`${API_BASE}/auth/login`, {
    data: { email: creds.email, password: creds.password },
  });
  if (!res.ok()) {
    const body = await res.text();
    throw new Error(
      `Login failed for ${creds.email}: ${res.status()} ${body.slice(0, 200)}`
    );
  }
  const json = await res.json();
  const data = json.data;
  if (!data || !data.tokens) {
    throw new Error(
      `Login response missing tokens for ${creds.email}: ${JSON.stringify(json).slice(0, 200)}`
    );
  }
  return {
    token: data.tokens.accessToken,
    refresh: data.tokens.refreshToken,
    user: data.user,
  };
}

/**
 * Inject auth tokens into localStorage so the web app considers the user
 * logged in. Must be called after navigating to an origin-matching URL.
 */
export async function injectAuth(
  page: Page,
  token: string,
  refresh: string
): Promise<void> {
  // Navigate to origin first so localStorage is writable for the right domain.
  await page.goto("/login", { waitUntil: "domcontentloaded" });
  await page.evaluate(
    ([t, r]) => {
      localStorage.setItem("medcore_token", t);
      localStorage.setItem("medcore_refresh", r);
    },
    [token, refresh]
  );
}

/**
 * Full login flow for a role: API login + cookie injection + navigate to
 * the dashboard. Returns the token for follow-up API calls.
 */
export async function loginAs(
  page: Page,
  request: APIRequestContext,
  role: Role
): Promise<string> {
  const creds = CREDS[role];
  const { token, refresh } = await apiLogin(request, creds);
  await injectAuth(page, token, refresh);
  await page.goto("/dashboard");
  // Wait for auth-gated UI to render rather than just a URL change.
  await expect(page.locator("text=MedCore").first()).toBeVisible({
    timeout: 15_000,
  });
  return token;
}

/**
 * Call an authed API endpoint using an access token.
 */
export async function apiGet(
  request: APIRequestContext,
  token: string,
  path: string
) {
  const res = await request.get(`${API_BASE}${path}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  return { status: res.status(), body: res.ok() ? await res.json() : null };
}

export async function apiPost(
  request: APIRequestContext,
  token: string,
  path: string,
  body: unknown
) {
  const res = await request.post(`${API_BASE}${path}`, {
    headers: { Authorization: `Bearer ${token}` },
    data: body,
  });
  return { status: res.status(), body: res.ok() ? await res.json() : null };
}

/**
 * Small helper: returns true if the E2E_FULL env var is set. Used to gate
 * tests that require real third-party API credentials (Razorpay, WhatsApp).
 */
export function isFullRun(): boolean {
  return process.env.E2E_FULL === "1" || process.env.E2E_FULL === "true";
}
