import { Page, APIRequestContext, expect } from "@playwright/test";

/**
 * API base URL used for server-side login.
 * Derived from E2E_API_URL, or falls back to localhost:4000/api/v1.
 */
export const API_BASE =
  process.env.E2E_API_URL || "http://localhost:4000/api/v1";

export type Role =
  | "ADMIN"
  | "DOCTOR"
  | "NURSE"
  | "RECEPTION"
  | "PATIENT"
  | "LAB_TECH"
  | "PHARMACIST";

export interface Credentials {
  email: string;
  password: string;
}

/**
 * Seeded demo credentials (from packages/db/src/seed-realistic.ts).
 * Tests that modify data should rely on faker and should be idempotent.
 */
export const CREDS: Record<Role, Credentials> = {
  ADMIN: { email: "admin@medcore.local", password: "admin123" },
  DOCTOR: { email: "dr.sharma@medcore.local", password: "doctor123" },
  NURSE: { email: "nurse@medcore.local", password: "nurse123" },
  RECEPTION: { email: "reception@medcore.local", password: "reception123" },
  // Patient credentials are generated by the realistic seeder in the form
  // patient{N}@medcore.local / patient123 — patient1@ always exists.
  PATIENT: { email: "patient1@medcore.local", password: "patient123" },
  LAB_TECH: { email: "labtech@medcore.local", password: "labtech123" },
  PHARMACIST: { email: "pharmacist@medcore.local", password: "pharmacist123" },
};

/**
 * POST /auth/login against the API and return the access token.
 * Uses page.request so cookies / rate-limit IP matches browser context.
 */
// Track recent auth attempts to proactively stay under the prod rate limit
// (API config: 30 auth reqs per 60s per IP). Each test usually triggers two
// auth calls: POST /auth/login and GET /auth/me (from loadSession in-browser).
const AUTH_WINDOW_MS = 60_000;
const AUTH_MAX_PER_WINDOW = 12; // Conservative — each test = up to 2 auth hits.
const authTimestamps: number[] = [];

async function throttleAuth(): Promise<void> {
  const now = Date.now();
  // Drop timestamps older than the window.
  while (authTimestamps.length && now - authTimestamps[0] > AUTH_WINDOW_MS) {
    authTimestamps.shift();
  }
  if (authTimestamps.length >= AUTH_MAX_PER_WINDOW) {
    const waitMs = AUTH_WINDOW_MS - (now - authTimestamps[0]) + 500;
    await new Promise((r) => setTimeout(r, Math.max(waitMs, 1000)));
    return throttleAuth();
  }
  authTimestamps.push(Date.now());
}

export async function apiLogin(
  request: APIRequestContext,
  creds: Credentials
): Promise<{ token: string; refresh: string; user: any }> {
  await throttleAuth();
  // Retry on 429 (prod rate limiting) and 5xx with backoff. Total worst-case
  // wait ~75s which fits inside the 90s test timeout. Auth limit is 30/min so
  // a full minute often has to pass before the bucket refills.
  const delays = [2000, 4000, 8000, 15_000, 20_000, 30_000];
  let lastStatus = 0;
  let lastBody = "";
  for (let attempt = 0; attempt <= delays.length; attempt++) {
    const res = await request.post(`${API_BASE}/auth/login`, {
      data: { email: creds.email, password: creds.password },
    });
    if (res.ok()) {
      const json = await res.json();
      const data = json.data;
      if (!data || !data.tokens) {
        throw new Error(
          `Login response missing tokens for ${creds.email}: ${JSON.stringify(json).slice(0, 200)}`
        );
      }
      return {
        token: data.tokens.accessToken,
        refresh: data.tokens.refreshToken,
        user: data.user,
      };
    }
    lastStatus = res.status();
    lastBody = await res.text();
    if (lastStatus !== 429 && lastStatus < 500) break;
    if (attempt < delays.length) {
      await new Promise((r) => setTimeout(r, delays[attempt]));
    }
  }
  throw new Error(
    `Login failed for ${creds.email}: ${lastStatus} ${lastBody.slice(0, 200)}`
  );
}

/**
 * Inject auth tokens into localStorage so the web app considers the user
 * logged in. Must be called after navigating to an origin-matching URL.
 */
export async function injectAuth(
  page: Page,
  token: string,
  refresh: string
): Promise<void> {
  // Navigate to origin first so localStorage is writable for the right domain.
  await page.goto("/login", { waitUntil: "domcontentloaded" });
  await page.evaluate(
    ([t, r]) => {
      localStorage.setItem("medcore_token", t);
      localStorage.setItem("medcore_refresh", r);
      // Pre-dismiss onboarding tour for every role so it doesn't intercept clicks.
      for (const role of [
        "ADMIN",
        "DOCTOR",
        "NURSE",
        "RECEPTION",
        "PATIENT",
        "LAB_TECH",
        "PHARMACIST",
      ]) {
        localStorage.setItem(`mc_tour_${role}`, "1");
      }
    },
    [token, refresh]
  );
}

/**
 * Navigate to a dashboard path but tolerate the app briefly redirecting to
 * /login if the in-browser /auth/me probe hits the prod rate limit. Re-injects
 * auth and retries up to a few times before giving up.
 */
export async function gotoDashboard(
  page: Page,
  request: APIRequestContext,
  role: Role,
  path: string
): Promise<void> {
  await page.goto(path, { waitUntil: "domcontentloaded" });
  for (let i = 0; i < 3; i++) {
    // Give React a moment to complete its first render.
    await page.waitForTimeout(600);
    if (!page.url().includes("/login")) return;
    // The app logged us out (likely /auth/me 429). Re-auth and retry.
    await page.waitForTimeout(4000);
    const { token, refresh } = await apiLogin(request, CREDS[role]);
    await page.evaluate(
      ([t, r]) => {
        localStorage.setItem("medcore_token", t);
        localStorage.setItem("medcore_refresh", r);
      },
      [token, refresh]
    );
    await page.goto(path, { waitUntil: "domcontentloaded" });
  }
}

/**
 * Dismiss the onboarding tour modal if it appears mid-test. Best-effort.
 */
export async function dismissTourIfPresent(page: Page): Promise<void> {
  const tour = page.locator('[aria-label="Product tour"]');
  if (await tour.isVisible().catch(() => false)) {
    const skip = page.getByRole("button", { name: /skip( tour)?|close|finish/i }).first();
    if (await skip.isVisible().catch(() => false)) {
      await skip.click().catch(() => undefined);
      await tour.waitFor({ state: "hidden", timeout: 3000 }).catch(() => undefined);
    }
  }
}

/**
 * Full login flow for a role: API login + cookie injection + navigate to
 * the dashboard. Returns the token for follow-up API calls.
 */
export async function loginAs(
  page: Page,
  request: APIRequestContext,
  role: Role
): Promise<string> {
  const creds = CREDS[role];
  const { token, refresh, user } = await apiLogin(request, creds);
  await injectAuth(page, token, refresh);

  // Transparently retry any 429 from the browser so rate-limiting in the
  // backend doesn't cascade into user-visible logout / empty pages during
  // long test runs. Special-case /auth/me to synthesize success on persistent
  // 429 so the app never redirects to /login.
  await page.route("**/api/v1/**", async (route) => {
    try {
      const headers = route.request().headers();
      if (!headers["authorization"]) {
        headers["authorization"] = `Bearer ${token}`;
      }
      let resp = await route.fetch({ headers });
      for (let attempt = 0; attempt < 3 && resp.status() === 429; attempt++) {
        await new Promise((r) => setTimeout(r, 2000 * (attempt + 1)));
        resp = await route.fetch({ headers });
      }
      if (resp.status() === 429 && /\/auth\/me$/.test(route.request().url())) {
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ success: true, data: user }),
        });
        return;
      }
      await route.fulfill({ response: resp });
    } catch {
      // Page likely closed mid-retry; swallow so Playwright doesn't mark the
      // test failed over a teardown race.
      try {
        await route.abort();
      } catch {}
    }
  });

  await page.goto("/dashboard");
  // Wait for auth-gated UI to render rather than just a URL change.
  await expect(page.locator("text=MedCore").first()).toBeVisible({
    timeout: 15_000,
  });
  return token;
}

/**
 * Call an authed API endpoint using an access token.
 */
export async function apiGet(
  request: APIRequestContext,
  token: string,
  path: string
) {
  const res = await request.get(`${API_BASE}${path}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  return { status: res.status(), body: res.ok() ? await res.json() : null };
}

export async function apiPost(
  request: APIRequestContext,
  token: string,
  path: string,
  body: unknown
) {
  const res = await request.post(`${API_BASE}${path}`, {
    headers: { Authorization: `Bearer ${token}` },
    data: body,
  });
  return { status: res.status(), body: res.ok() ? await res.json() : null };
}

/**
 * Small helper: returns true if the E2E_FULL env var is set. Used to gate
 * tests that require real third-party API credentials (Razorpay, WhatsApp).
 */
export function isFullRun(): boolean {
  return process.env.E2E_FULL === "1" || process.env.E2E_FULL === "true";
}

// ─── Shared assertion helpers ────────────────────────────────────────────

/**
 * Assert that the page didn't bounce to the universal Access-Denied surface
 * (`/dashboard/not-authorized`) AND the rendered body doesn't contain a
 * raw "forbidden" / "403" string. Many specs re-implement these two
 * assertions inline; consolidating here keeps the negative-RBAC checks
 * in lockstep across the suite.
 */
export async function expectNotForbidden(page: Page): Promise<void> {
  expect(page.url()).not.toContain("/dashboard/not-authorized");
  await expect(page.locator("body")).not.toContainText(/forbidden|403/i);
}

// ─── Network stubbing ────────────────────────────────────────────────────

/**
 * Register a fulfill-with-static-JSON route. Wraps the boilerplate that
 * AI specs repeat inline:
 *
 *     await page.route(pattern, route => route.fulfill({
 *       status: 200,
 *       contentType: "application/json",
 *       body: JSON.stringify(body),
 *     }));
 *
 * NOTE: Playwright keeps the route registered until the test calls
 * `page.unroute(pattern)`. Subsequent matching requests will all be
 * fulfilled with the same body. If a test needs different responses on
 * later requests, it must `unroute` first and re-register.
 */
export async function stubAi(
  page: Page,
  urlPattern: string | RegExp,
  body: unknown,
  status: number = 200
): Promise<void> {
  await page.route(urlPattern, (route) =>
    route.fulfill({
      status,
      contentType: "application/json",
      body: JSON.stringify(body),
    })
  );
}

// ─── Deterministic data seeding ──────────────────────────────────────────

/**
 * `seedFixture(api, kind)` family: create a deterministic record via the
 * API and return its IDs. Specs that need a known patient currently scrape
 * `.first()` from a list, which is fragile when other tests mutate state.
 *
 * The `api` argument is a Playwright `APIRequestContext` already
 * authenticated as ADMIN or RECEPTION (i.e. created with extraHTTPHeaders
 * containing the bearer token).
 *
 * All helpers here rely on the API's own validation — if a payload shape
 * drifts (e.g. createPatientSchema gains a required field), the helper
 * throws a clear error referencing the failing endpoint instead of
 * letting the spec fail later with a confusing "patient not found".
 */

function rand(): string {
  return Math.random().toString(36).slice(2, 10);
}

function indianishName(): string {
  // Realistic-seed compatible: avoids the "test1/aaa/qwerty" anti-pattern
  // listed in docs/TESTER_PROMPT.md so screenshots from a seeded test run
  // can survive marketing review.
  const firsts = [
    "Aarav",
    "Saanvi",
    "Vihaan",
    "Diya",
    "Reyansh",
    "Priya",
    "Rahul",
    "Anaya",
    "Meera",
    "Mohammed",
  ];
  const lasts = [
    "Mehta",
    "Joshi",
    "Reddy",
    "Sharma",
    "Gupta",
    "Krishnan",
    "Verma",
    "Iyer",
    "Khan",
    "Patel",
  ];
  return `${firsts[Math.floor(Math.random() * firsts.length)]} ${lasts[Math.floor(Math.random() * lasts.length)]}`;
}

export interface SeedPatientResult {
  id: string;
  mrNumber: string;
  name: string;
}

export async function seedPatient(
  api: APIRequestContext,
  opts: { name?: string } = {}
): Promise<SeedPatientResult> {
  const name = opts.name ?? indianishName();
  const res = await api.post(`${API_BASE}/patients`, {
    data: {
      name,
      age: 30 + Math.floor(Math.random() * 30),
      gender: "MALE",
      phone: `+9198${Math.floor(10_000_000 + Math.random() * 89_999_999)}`,
    },
  });
  if (!res.ok()) {
    throw new Error(
      `seedPatient failed: ${res.status()} ${(await res.text()).slice(0, 200)}`
    );
  }
  const json = await res.json();
  const data = json.data ?? json;
  return {
    id: data.id,
    mrNumber: data.mrNumber,
    name: data.user?.name ?? data.name ?? name,
  };
}

export interface SeedAppointmentResult {
  id: string;
  scheduledAt: string;
}

export async function seedAppointment(
  api: APIRequestContext,
  opts: { patientId: string; doctorId?: string }
): Promise<SeedAppointmentResult> {
  // Resolve a doctorId if the caller didn't pass one. The walk-in endpoint
  // requires both UUIDs so we pick the first active doctor we can see.
  let doctorId = opts.doctorId;
  if (!doctorId) {
    const res = await api.get(`${API_BASE}/doctors`);
    if (!res.ok()) {
      throw new Error(
        `seedAppointment: cannot list doctors: ${res.status()} ${(await res.text()).slice(0, 200)}`
      );
    }
    const json = await res.json();
    const list = json.data ?? json;
    const first = Array.isArray(list) ? list[0] : list?.doctors?.[0];
    if (!first?.id) {
      throw new Error("seedAppointment: no doctor available to anchor walk-in");
    }
    doctorId = first.id;
  }
  const res = await api.post(`${API_BASE}/appointments/walk-in`, {
    data: {
      patientId: opts.patientId,
      doctorId,
      priority: "NORMAL",
      notes: "E2E seeded walk-in",
    },
  });
  if (!res.ok()) {
    throw new Error(
      `seedAppointment failed: ${res.status()} ${(await res.text()).slice(0, 200)}`
    );
  }
  const json = await res.json();
  const data = json.data ?? json;
  return {
    id: data.id,
    scheduledAt: data.scheduledAt ?? data.checkInTime ?? new Date().toISOString(),
  };
}

export interface SeedAdmissionResult {
  id: string;
  bedId: string;
}

export async function seedAdmission(
  api: APIRequestContext,
  opts: { patientId: string; doctorId?: string; bedId?: string }
): Promise<SeedAdmissionResult> {
  let doctorId = opts.doctorId;
  if (!doctorId) {
    const res = await api.get(`${API_BASE}/doctors`);
    if (!res.ok()) {
      throw new Error(
        `seedAdmission: cannot list doctors: ${res.status()} ${(await res.text()).slice(0, 200)}`
      );
    }
    const json = await res.json();
    const list = json.data ?? json;
    const first = Array.isArray(list) ? list[0] : list?.doctors?.[0];
    if (!first?.id) {
      throw new Error("seedAdmission: no doctor available to admit under");
    }
    doctorId = first.id;
  }
  let bedId = opts.bedId;
  if (!bedId) {
    // Find any AVAILABLE bed. The endpoint shape varies slightly between
    // /beds and /wards — try the flat list first.
    const res = await api.get(`${API_BASE}/beds?status=AVAILABLE`);
    if (res.ok()) {
      const json = await res.json();
      const list = json.data ?? json;
      const first = Array.isArray(list) ? list[0] : list?.beds?.[0];
      if (first?.id) bedId = first.id;
    }
  }
  if (!bedId) {
    throw new Error(
      "seedAdmission: no bedId provided and no AVAILABLE bed found via /beds"
    );
  }
  const res = await api.post(`${API_BASE}/admissions`, {
    data: {
      patientId: opts.patientId,
      doctorId,
      bedId,
      reason: "E2E seeded admission",
      admissionType: "EMERGENCY",
    },
  });
  if (!res.ok()) {
    throw new Error(
      `seedAdmission failed: ${res.status()} ${(await res.text()).slice(0, 200)}`
    );
  }
  const json = await res.json();
  const data = json.data ?? json;
  return { id: data.id, bedId: data.bedId ?? bedId };
}

// ─── Throwaway PATIENT identity for state-leakage-free specs ─────────────

export interface FreshPatientResult {
  token: string;
  refresh: string;
  patientId: string;
  userId: string;
  email: string;
  password: string;
}

/**
 * Create a brand-new PATIENT via /auth/register and return the access
 * token + IDs. Specs that need a clean patient context can't reuse the
 * static `patient1@medcore.local` because state leaks across tests
 * (consents, feedback, exports etc. accumulate over the session).
 *
 * Email collisions are avoided by suffixing with Date.now()+rand().
 * The password meets `strongPassword` requirements (mixed case, digits,
 * symbol, ≥10 chars) so the registration validator accepts it.
 */
export async function freshPatientToken(
  api: APIRequestContext
): Promise<FreshPatientResult> {
  const email = `pw-${Date.now()}-${rand()}@medcore.local`;
  // Strong-password requirement (see packages/shared/src/utils/password.ts):
  // ≥10 chars, upper+lower+digit+symbol, not in denylist.
  const password = `Pw!E2e-${rand()}-Aa9`;
  const res = await api.post(`${API_BASE}/auth/register`, {
    data: {
      name: indianishName(),
      email,
      phone: `+9198${Math.floor(10_000_000 + Math.random() * 89_999_999)}`,
      password,
      role: "PATIENT",
    },
  });
  if (!res.ok()) {
    throw new Error(
      `freshPatientToken failed: ${res.status()} ${(await res.text()).slice(0, 200)}`
    );
  }
  const json = await res.json();
  const data = json.data ?? json;
  // /auth/register responds with `data.user` (no embedded patient id), so
  // resolve the patient row via /auth/me using the freshly minted token.
  const token: string = data.tokens?.accessToken ?? data.accessToken;
  const refresh: string = data.tokens?.refreshToken ?? data.refreshToken;
  const userId: string = data.user?.id;
  // Best-effort patient-id lookup. If the endpoint shape changes, callers
  // can still use `userId` to find the patient downstream.
  let patientId = "";
  try {
    const me = await api.get(`${API_BASE}/auth/me`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (me.ok()) {
      const meJson = await me.json();
      patientId = meJson.data?.patient?.id ?? meJson.data?.patientId ?? "";
    }
  } catch {
    // swallow — patientId is best-effort
  }
  return { token, refresh, patientId, userId, email, password };
}
